# docker-compose.yml
version: "3.7"
services:

  frontend:
    build: frontend
    expose:
      - "80"

  app:
    build: backend
    command: npm start
    environment: 
      DOTENVENC_KEY: $DOTENVENC_KEY
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      TMDB_API_KEY: $TMDB_API_KEY
      JWT_SECRET: ${DOTENVENC_KEY:?err}
    depends_on:
      - postgres
    expose:
      - "3000"
      - "9229"
    volumes:
      - ${NAS_MOVIES_DIR:?err}:/mnt/nas/movies
      - './logs:/home/app/logs'

  postgres:
    build: database
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      DB_DUMP_PW: ${DB_DUMP_PW?err}
    volumes:
      - './db_backups:/backups'
    expose:
      - "5432"
    
